- src/shared/stores/__tests__/__snapshots__/base.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/comments.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/lang.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/menu.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/scroll.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/shareModal.tests.js.snap
- src/shared/stores/__tests__/base.tests.js
- src/shared/stores/__tests__/comments.tests.js
- src/shared/stores/__tests__/lang.tests.js
- src/shared/stores/__tests__/menu.tests.js
- src/shared/stores/__tests__/scroll.tests.js
- src/shared/stores/__tests__/shareModal.tests.js
fixes https://github.com/frontity/saturn-theme/issues/23
> test(shared): improves shared stores tests

- src/pwa/components/Gdpr/Styles.js
> Remove GDPR "configuration" button

- src/shared/components/Theme/Title.js
Fixes https://github.com/frontity/wp-org-connection/issues/20
> Get title from headMeta.pagedTitle view

- src/shared/stores/__tests__/scroll.tests.js
- src/shared/stores/scroll.js
Fixes https://github.com/frontity/saturn-theme/issues/29
> Fixes handleScroll logic

- src/pwa/components/Slider/index.js
Fixes https://github.com/frontity/saturn-theme/issues/17
> Change componentDidMount and updateActiveSlide functions in Slider

- src/pwa/components/Post/Body.js
- src/pwa/components/ShareBar/ShareLink.js
- src/shared/components/Post/SharedCount.js
fixes https://github.com/frontity/saturn-theme/issues/37
> Fixes different react warnings (keys and props)

- src/pwa/components/Comments/index.js
- src/pwa/components/Gdpr/index.js
- src/shared/stores/__tests__/__snapshots__/base.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/comments.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/lang.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/shareModal.tests.js.snap
- src/shared/stores/languages/en.json
- src/shared/stores/languages/es.json
fixes https://github.com/frontity/saturn-theme/issues/44
> Adds missing translations

- src/amp/components/ShareBar/FacebookShare.js
- src/amp/components/ShareBar/Shares.js
- src/shared/styled/ShareBar/NextButton.js
fixes https://github.com/frontity/saturn-theme/issues/46
> Changes styles in amp share bar

- src/shared/components/Image/index.js
fixes https://github.com/frontity/saturn-theme/issues/57
> Fixes error in Image component when `content` prop is undefined

- src/pwa/components/Post/Body.js
- src/pwa/components/Post/TagList.js
fixes https://github.com/frontity/saturn-theme/issues/58
> Fixes this component not rendering on custom post type

- src/shared/components/LazyAudio/index.js
- src/shared/converters/audio.js
fixes https://github.com/frontity/saturn-theme/issues/63
> Fixes styles in LazyAudio

- src/shared/components/LazySoundcloud/index.js
- src/shared/converters/iframe.js
- src/shared/converters/index.js
- src/shared/converters/soundcloud.js
fixes https://github.com/frontity/saturn-theme/issues/62
> Adds support for Soundcloud and fixes iframes in AMP

- src/shared/components/Content/index.js
- src/shared/components/LazyIframe/index.js
- src/shared/processors/index.js
- src/shared/processors/removeAmpListTypes.js
fixes https://github.com/frontity/saturn-theme/issues/60
> Fixes amp-iframe, ul, ol, and li tags in AMP

- src/shared/converters/index.js
- src/shared/converters/removeWpEmbeddedContent.js
fixes https://github.com/frontity/saturn-theme/issues/78
> Removes wp-embedded-content with a converter

- src/pwa/components/ContentCarousel/index.js
- src/pwa/components/Contexts/Column.js
- src/pwa/components/List/index.js
- src/pwa/components/Media/index.js
- src/pwa/components/Theme/index.js
- src/shared/components/Content/index.js
- src/shared/components/HtmlToReactConverter/index.js
- src/shared/components/HtmlToReactConverter/injectSlots.js
- src/shared/components/SlotInjector/index.js
> Change SlotInjector to use strings and place carousels inside Content using slots

- src/shared/components/Image/index.js
- src/shared/converters/image.js
fixes https://github.com/frontity/saturn-theme/issues/81
> Fixes Image and converter for incomplete src and srcset

- src/amp/components/Theme/index.js
- src/pwa/components/Contexts/Column.js
- src/shared/components/MyRFooter/index.js
fixes https://github.com/frontity/saturn-theme/issues/87
> Adds config for new site to MyR footer

- src/shared/components/HtmlToReactConverter/injectSlots.js
- src/shared/components/SlotInjector/index.js
fixes https://github.com/frontity/saturn-theme/issues/91
> Fixes react warnings about keys in html2react

- package-lock.json
- src/shared/components/HtmlToReactConverter/injectSlots.js
- src/shared/components/LazyIframe/index.js
- src/shared/components/Spinner/index.js
- src/shared/converters/iframe.js
fixes https://github.com/frontity/saturn-theme/issues/85
> Adds support for resizable iframes

- src/shared/components/Content/index.js
- src/shared/components/LazyIframe/index.js
- src/shared/converters/iframe.js
fixes https://github.com/frontity/saturn-theme/issues/97
> Fixes iframe styles

- src/pwa/components/Media/index.js
- src/shared/components/SlotInjector/index.js
fixes https://github.com/frontity/saturn-theme/issues/99
> Fixes Media missing mstId prop

- src/shared/components/MyRFooter/Powered.js
fixes https://github.com/frontity/saturn-theme/issues/114
> Changes text Worona for Frontity in MyR Footer,

- src/shared/components/HtmlToReactConverter/index.js
- src/shared/processors/index.js
- src/shared/processors/removeAmpColWidth.js
- src/shared/processors/removeAmpIds.js
- src/shared/processors/removeAmpListTypes.js
fixes https://github.com/frontity/saturn-theme/issues/115
> Fixes col tag bug in AMP and refactors processors

- src/shared/converters/youtube.js
fixes https://github.com/frontity/saturn-theme/issues/123
> Support iframe data-src attribute in youtube converter

- src/amp/components/Theme/index.js
- src/pwa/components/Contexts/Column.js
- src/shared/components/MyRFooter/index.js
fixes https://github.com/frontity/saturn-theme/issues/122
> feat(myr-footer): move footer settings to db

- src/amp/components/Post/index.js
- src/pwa/components/Comments/index.js
- src/pwa/components/Contexts/Context.js
- src/pwa/components/ListBar/index.js
- src/pwa/components/Media/index.js
- src/pwa/components/Menu/index.js
- src/pwa/components/NotificationsButton/index.js
- src/pwa/components/NotificationsSwitch/index.js
- src/pwa/components/Post/index.js
- src/pwa/components/PostBar/index.js
- src/pwa/components/Share/ShareCopy.js
- src/pwa/components/Share/ShareTotal.js
- src/pwa/components/Share/index.js
- src/pwa/components/Slider/index.js
- src/shared/components/LazyAnimated/index.js
- src/shared/components/Post/SharedCount.js
- src/shared/helpers/index.js
- src/shared/styled/ShareBar/index.js
> Reduce animation time in the existing animations

- package-lock.json
- package.json
- src/pwa/components/Theme/index.js
- src/pwa/stores/client.js
- src/shared/components/Image/index.js
fixes https://github.com/frontity/saturn-theme/issues/111
> Implementation of vanilla-lazyload

- src/pwa/components/ListBar/Logo.js
- src/pwa/components/ListBar/index.js
- src/pwa/components/Menu/MenuLogo.js
- src/pwa/components/PostBar/index.js
- src/pwa/stores/client.js
- src/shared/components/Content/index.js
- src/shared/components/Image/index.js
- src/shared/converters/image.js
fixes https://github.com/frontity/saturn-theme/issues/135
> Fixes lazyload classes conflict

- src/pwa/components/Post/Body.js
fixes https://github.com/frontity/saturn-theme/issues/134
> Add support for new @frontity/lazyload

- package-lock.json
- package.json
- src/shared/stores/__tests__/__snapshots__/base.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/comments.tests.js.snap
- src/shared/stores/__tests__/__snapshots__/shareModal.tests.js.snap
- src/shared/stores/__tests__/shareModal.tests.js
- src/shared/stores/index.js
- src/shared/stores/lang.js
fixes https://github.com/frontity/frontity/issues/85
> Update to MST 3

- src/amp/components/ShareBar/FacebookShare.js
- src/shared/components/Image/index.js
fixes https://github.com/frontity/saturn-theme/issues/140
> Fix image and share bar styles in AMP

- src/shared/processors/high/index.js
- src/shared/processors/medium/index.js
- src/shared/processors/medium/injectSlots.js
- src/shared/stores/index.js
Fixes https://github.com/frontity/saturn-theme/issues/148
> Add 'restartCount' processor with high priority

- package-lock.json
- package.json
Fixes https://github.com/frontity/frontity/issues/112
> Update h2r version

- src/pwa/components/Contexts/Column.js
- src/pwa/components/List/index.js
- src/shared/components/Content/index.js
- src/shared/components/SlotInjector/index.js
- src/shared/processors/medium/injectSlots.js
Closes https://github.com/frontity/frontity/issues/69
> Create 'isAboveTheFold' prop in SlotInjector and use it in the PWA

- src/shared/stores/__tests__/base.tests.js
- src/shared/stores/index.js
Fixes https://github.com/frontity/wp-org-connection/issues/43
> Fix and refactor getNextPage action

- src/pwa/components/ListBar/Nav.js
- src/pwa/components/Menu/MenuList.js
- src/shared/contexts/index.js
- src/shared/stores/index.js
> Add the correct id when type is 'latest'

- src/shared/components/Image/index.js
fixes https://github.com/frontity/saturn-theme/issues/169
> Fix images not visible in AMP

- src/pwa/components/List/ListItemNoFeatured.js
- src/pwa/components/List/index.js
- src/shared/components/Post/FeaturedImage.js
> Don't show placeholder when there is no image in a post

- src/pwa/components/List/ListItemNoMedia.js
- src/pwa/components/List/index.js
Fixes https://github.com/frontity/wp-org-connection/issues/8
> Hide post image if there isn't featured or content media

- src/amp/components/Post/index.js
- src/pwa/components/Contexts/Column.js
- src/pwa/components/Post/index.js
- src/pwa/components/SameHeight/index.js
- src/shared/components/Post/Header.js
> Fix styles when there is no featured image in posts

- src/pwa/components/List/index.js
- src/pwa/components/Share/SharePreview.js
fixes https://github.com/frontity/saturn-theme/issues/180
> Fix list image and share image to use content

- src/pwa/components/Carousel/index.js
fixes https://github.com/frontity/saturn-theme/issues/180
> Fix carousel using content images

- src/shared/processors/low/image.js
fixes https://github.com/frontity/frontity/issues/136
> Fixes images context when there isn't a featured image

- src/shared/processors/low/index.js
- src/shared/processors/low/removeWpEmbeddedContent.js
> Delete 'removeWpEmbeddedContent' processor

- src/pwa/components/Post/index.js
- src/pwa/components/SameHeight/index.js
- src/shared/components/LazyAnimated/index.js
fixes https://github.com/frontity/saturn-theme/issues/189
> Fixes overridden min-height in SameHeight

- src/amp/components/PostBar/index.js
- src/amp/components/Theme/index.js
- src/pwa/components/Contexts/Context.js
- src/pwa/components/ListBar/index.js
- src/pwa/components/Post/Body.js
- src/pwa/components/PostBar/index.js
- src/shared/components/Post/Header.js
Adds `'before navbar'`, `'after comments'`, `'after next posts'` and `'after more in 1 '` slots.
Closes https://github.com/frontity/ads-form/issues/62
> Add extra slots for placing ads

- src/amp/components/Theme/index.js
- src/pwa/components/Contexts/Column.js
- src/pwa/components/Contexts/Context.js
- src/pwa/components/NavbarSlotPlaceholder/index.js
Closes https://github.com/frontity/ads-form/issues/62
> Fix 'before navbar' and add 'before item' and 'after item' slots

- src/shared/components/Content/index.js
fixes https://github.com/frontity/saturn-theme/issues/199
> Adds .ignored-by-content to prevent applying styles

- package-lock.json
- package.json
> Update H2R package version

- src/amp/components/Post/index.js
- src/pwa/components/Contexts/Column.js
- src/shared/components/Post/Featured.js
- src/shared/components/Post/FeaturedImage.js
- src/shared/components/Post/FeaturedVideo.js
- src/shared/components/Post/Header.js
- src/shared/components/SlotInjector/index.js
> Add featured video if it exists

- src/pwa/components/Contexts/Column.js
> Feature-video: check if entity.raw exists before using entity.raw.featured_video

- src/pwa/components/Comments/index.js
Closes https://github.com/frontity/disqus-comments/issues/1
> Render Comments component if there are comments settings
